name: triggering_code

on: 
    workflow_dispatch:
#   push:  
#        paths:
#            - 'speech/speechInteraction/modules/**'


jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:
        - name: Get Token
          id: get_workflow_token
          uses: tibdex/github-app-token@v1
          with:
            private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
            app_id: ${{ secrets.APPLICATION_ID }}
            repository: icub-tech-iit/code
            
        - name: Repository dispatch to code
          uses: peter-evans/repository-dispatch@v1
          env:
            GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          with:
            token: ${{ env.GITHUB_APPS_TOKEN }}
            repository: icub-tech-iit/code
            event-type: repository_trigger
            client-payload: '{"type": "repository_trigger", "img_list": "speech"}'

